import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import AirbnbMark from "../../components/AirbnbMark";

function Register() {
  const navigate = useNavigate(); const [form, setForm] = useState({ username:"", email:"", password:"" }); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setMessage(""); setLoading(true); try { const response = await fetch("https://airbnb-capstone-server.onrender.com/", { method:"POST", headers:{ "Content-Type":"application/json" }, body:JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Registration failed"); setMessage("Account created. Signing you in..."); const login = await fetch("https://airbnb-capstone-server.onrender.com/", { method:"POST", headers:{ "Content-Type":"application/json" }, body:JSON.stringify({ email:form.email, password:form.password }) }); const loginData = await login.json(); if (!login.ok) throw new Error(loginData.message || "Account created, but sign-in failed"); localStorage.setItem("token", loginData.token); localStorage.setItem("user", JSON.stringify(loginData.user)); navigate("/"); } catch (error) { setMessage(error.message); } finally { setLoading(false); } };
  return <div className="login-page"><div className="login-card"><Link to="/" className="login-brand"><span className="admin-brand-mark"><AirbnbMark /></span>Airbnb</Link><p className="admin-kicker">JOIN AIRBNB</p><h1>Create account</h1><p>Sign up to save stays and make reservations.</p><form onSubmit={submit}><label>Username</label><input value={form.username} minLength="2" onChange={(e) => setForm({ ...form, username:e.target.value })} placeholder="Your name" required /><label>Email Address</label><input type="email" value={form.email} onChange={(e) => setForm({ ...form, email:e.target.value })} placeholder="you@example.com" required /><label>Password</label><input type="password" value={form.password} minLength="6" onChange={(e) => setForm({ ...form, password:e.target.value })} placeholder="At least 6 characters" required /><button type="submit" disabled={loading}>{loading ? "Creating account..." : "Create account"}</button></form>{message && <p className="login-message">{message}</p>}<p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></div></div>;
}
export default Register;
